# Generated by Django 4.1.5 on 2023-01-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
