# Generated by Django 4.1.1 on 2022-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(default='NO Comments', max_length=40),
        ),
    ]
