# Generated by Django 4.1.1 on 2022-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='stumail',
            field=models.EmailField(default='Email is not given', max_length=254),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stuid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
