# Generated by Django 4.1.1 on 2022-10-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_stuinfo_stumail_alter_stuinfo_stuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuinfo',
            new_name='students',
        ),
    ]
